swagger: "2.0"
info:
    title: 流程编辑器 API
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /account:
        get:
            tags:
                - account
            summary: getAccount account
            description: Get account
            operationId: account#getAccount
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AccountGetAccountResponseBody'
                        required:
                            - user_id
                            - activated
                            - membership
            schemes:
                - http
    /flow:
        get:
            tags:
                - flow
            summary: getFlowList flow
            description: 列出当前用户拥有的 flow
            operationId: flow#getFlowList
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/FlowListItemDataResponse'
            schemes:
                - http
        post:
            tags:
                - flow
            summary: createFlow flow
            description: 创建 flow
            operationId: flow#createFlow
            parameters:
                - name: CreateFlowRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FlowCreateFlowRequestBody'
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/FlowCreateFlowResponseBody'
                        required:
                            - id
                            - title
                            - created_at
            schemes:
                - http
    /flow/{id}:
        get:
            tags:
                - flow
            summary: getFlow flow
            description: 根据 flow id 获取 flow 详情
            operationId: flow#getFlow
            parameters:
                - name: id
                  in: path
                  description: 要获取的 flow id
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FlowGetFlowResponseBody'
                        required:
                            - id
                            - title
                            - created_at
            schemes:
                - http
        put:
            tags:
                - flow
            summary: updateFlow flow
            description: 更新 flow
            operationId: flow#updateFlow
            parameters:
                - name: id
                  in: path
                  description: 要更新的 flow id
                  required: true
                  type: string
                - name: UpdateFlowRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FlowUpdateFlowRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/FlowUpdateFlowResponseBody'
                        required:
                            - id
                            - title
                            - created_at
            schemes:
                - http
        delete:
            tags:
                - flow
            summary: deleteFlow flow
            description: 删除 flow
            operationId: flow#deleteFlow
            parameters:
                - name: id
                  in: path
                  description: 要删除的 flow id
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /flow/{id}/copy:
        post:
            tags:
                - flow
            summary: copyFlow flow
            description: 复制 flow
            operationId: flow#copyFlow
            parameters:
                - name: id
                  in: path
                  description: 要复制的 flow id
                  required: true
                  type: string
            responses:
                "201":
                    description: Created response.
            schemes:
                - http
definitions:
    AccountGetAccountResponseBody:
        title: AccountGetAccountResponseBody
        type: object
        properties:
            activated:
                type: boolean
                example: false
            membership:
                type: integer
                example: 5198081747063490700
                format: int64
            roles:
                type: array
                items:
                    type: string
                    example: Voluptatibus autem sapiente et sequi.
                example:
                    - Aut omnis distinctio.
                    - Consequatur velit libero.
                    - Deleniti dolorum vel.
                    - Non illum possimus.
            user_id:
                type: string
                example: Voluptate temporibus vitae asperiores omnis odio.
        example:
            activated: true
            membership: 5905438953811239422
            roles:
                - Impedit quo nihil ut repellendus molestiae consequuntur.
                - Et voluptas quod possimus earum repudiandae.
                - Nobis est deserunt blanditiis rerum.
            user_id: Tenetur ipsam laboriosam.
        required:
            - user_id
            - activated
            - membership
    FlowCreateFlowRequestBody:
        title: FlowCreateFlowRequestBody
        type: object
        properties:
            edges:
                type: string
                description: flow 边
                example: Cumque odio fuga.
            nodes:
                type: string
                description: flow 节点
                example: Ut non ut.
            title:
                type: string
                description: flow 标题
                example: Aut aperiam repellendus fugit facilis.
        example:
            edges: Voluptas optio consectetur quo possimus nobis.
            nodes: Reiciendis eligendi nostrum odit voluptatem.
            title: Voluptas minima et exercitationem omnis ipsum deserunt.
    FlowCreateFlowResponseBody:
        title: FlowCreateFlowResponseBody
        type: object
        properties:
            created_at:
                type: string
                description: flow 创建时间
                example: Ut quis et repellat facere et.
            edges:
                type: string
                description: flow 边
                example: Modi dignissimos non perferendis possimus sint.
            id:
                type: integer
                description: flow id
                example: 4187506608466379594
                format: int64
            nodes:
                type: string
                description: flow 节点
                example: At optio ex quae.
            title:
                type: string
                description: flow 标题
                example: Tempore beatae distinctio dolorem reprehenderit aliquam.
        example:
            created_at: Atque dolor tempore alias ut.
            edges: Nesciunt ad dolores aut incidunt sit architecto.
            id: 1213080747031818249
            nodes: Nihil eius unde consequatur.
            title: Iure assumenda quos quae consequuntur beatae.
        required:
            - id
            - title
            - created_at
    FlowGetFlowResponseBody:
        title: FlowGetFlowResponseBody
        type: object
        properties:
            created_at:
                type: string
                description: flow 创建时间
                example: Est optio aperiam.
            edges:
                type: string
                description: flow 边
                example: Repellat corrupti reprehenderit.
            id:
                type: integer
                description: flow id
                example: 6882596758243384156
                format: int64
            nodes:
                type: string
                description: flow 节点
                example: Provident veniam porro ducimus voluptatem consequatur asperiores.
            title:
                type: string
                description: flow 标题
                example: Quis delectus.
        example:
            created_at: Facilis deserunt.
            edges: Magnam repudiandae error numquam.
            id: 7244976131529825890
            nodes: Iste ab.
            title: In itaque et.
        required:
            - id
            - title
            - created_at
    FlowListItemDataResponse:
        title: FlowListItemDataResponse
        type: object
        properties:
            created_at:
                type: string
                description: flow 创建时间
                example: Minus doloremque blanditiis consequatur voluptate et.
            id:
                type: integer
                description: flow id
                example: 7816148651312659555
                format: int64
            title:
                type: string
                description: flow 标题
                example: Et sed culpa vitae.
        example:
            created_at: In quibusdam reprehenderit dolorem nesciunt alias labore.
            id: 8062358120128855813
            title: Deleniti et est quas.
        required:
            - id
            - title
            - created_at
    FlowUpdateFlowRequestBody:
        title: FlowUpdateFlowRequestBody
        type: object
        properties:
            edges:
                type: string
                description: flow 边
                example: Libero maxime.
            nodes:
                type: string
                description: flow 节点
                example: Voluptas aperiam.
            title:
                type: string
                description: flow 标题
                example: Ut sed quas et voluptatum.
        example:
            edges: Adipisci explicabo eveniet cum unde quam.
            nodes: In et fugiat.
            title: Veritatis vel voluptate rerum minus.
    FlowUpdateFlowResponseBody:
        title: FlowUpdateFlowResponseBody
        type: object
        properties:
            created_at:
                type: string
                description: flow 创建时间
                example: Consequatur et neque.
            edges:
                type: string
                description: flow 边
                example: Illo qui repudiandae ipsum aut distinctio.
            id:
                type: integer
                description: flow id
                example: 7895679563155964847
                format: int64
            nodes:
                type: string
                description: flow 节点
                example: Fuga beatae et suscipit autem.
            title:
                type: string
                description: flow 标题
                example: In molestias.
        example:
            created_at: Voluptatem quis nihil voluptatem porro.
            edges: Ex maiores.
            id: 2062647879852682326
            nodes: Magnam maxime repudiandae consequatur ratione.
            title: Eaque rerum reprehenderit autem.
        required:
            - id
            - title
            - created_at
