openapi: 3.0.3
info:
    title: 流程编辑器 API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for flow-editor-server
paths:
    /account:
        get:
            tags:
                - account
            summary: getAccount account
            description: Get account
            operationId: account#getAccount
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AccountInfo'
                            example:
                                activated: true
                                membership: 7755093410145240675
    /flow:
        get:
            tags:
                - flow
            summary: getFlowList flow
            description: 列出当前用户拥有的 flow
            operationId: flow#getFlowList
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/FlowListItem'
                                example:
                                    - created_at: Corporis totam.
                                      id: 5733579738933068263
                                      title: Nam fugiat perferendis est tempora in.
                                    - created_at: Corporis totam.
                                      id: 5733579738933068263
                                      title: Nam fugiat perferendis est tempora in.
                            example:
                                - created_at: Corporis totam.
                                  id: 5733579738933068263
                                  title: Nam fugiat perferendis est tempora in.
                                - created_at: Corporis totam.
                                  id: 5733579738933068263
                                  title: Nam fugiat perferendis est tempora in.
                                - created_at: Corporis totam.
                                  id: 5733579738933068263
                                  title: Nam fugiat perferendis est tempora in.
                                - created_at: Corporis totam.
                                  id: 5733579738933068263
                                  title: Nam fugiat perferendis est tempora in.
        post:
            tags:
                - flow
            summary: createFlow flow
            description: 创建 flow
            operationId: flow#createFlow
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateFlowRequestBody'
                        example:
                            edges: Veniam omnis repellendus.
                            nodes: Ut omnis quam.
                            title: Veritatis reprehenderit placeat quis.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetail'
                            example:
                                created_at: Qui ipsa.
                                edges: Est ab est illo sequi.
                                id: 7586672659878409806
                                nodes: Iure quia quam at repudiandae.
                                title: Impedit beatae nihil voluptas laudantium fugit.
    /flow/{id}:
        delete:
            tags:
                - flow
            summary: deleteFlow flow
            description: 删除 flow
            operationId: flow#deleteFlow
            parameters:
                - name: id
                  in: path
                  description: 要删除的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要删除的 flow id
                    example: Doloribus vel quidem occaecati veniam.
                  example: Architecto earum soluta pariatur voluptatem voluptatem beatae.
            responses:
                "204":
                    description: No Content response.
        get:
            tags:
                - flow
            summary: getFlow flow
            description: 根据 flow id 获取 flow 详情
            operationId: flow#getFlow
            parameters:
                - name: id
                  in: path
                  description: 要获取的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要获取的 flow id
                    example: Et sint officia aut est omnis.
                  example: Excepturi sit alias minus omnis.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetail'
                            example:
                                created_at: Delectus autem.
                                edges: Vitae quidem non earum sed.
                                id: 2015585179657686444
                                nodes: Sunt et consequatur consequatur et.
                                title: Sapiente sint.
        put:
            tags:
                - flow
            summary: updateFlow flow
            description: 更新 flow
            operationId: flow#updateFlow
            parameters:
                - name: id
                  in: path
                  description: 要更新的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要更新的 flow id
                    example: Quo architecto sed aperiam ullam debitis nam.
                  example: Est sequi sit atque minus vel.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateFlowRequestBody'
                        example:
                            edges: Quis dolor cum consequuntur eligendi fugit qui.
                            nodes: Dolore illum et consequatur quis voluptatum.
                            title: Asperiores reiciendis corporis aliquam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FlowDetail'
                            example:
                                created_at: At laborum molestiae vel consequuntur quia.
                                edges: A et ut accusantium quo maxime omnis.
                                id: 7028823793012778726
                                nodes: Ut porro.
                                title: Error non tempore.
    /flow/{id}/copy:
        post:
            tags:
                - flow
            summary: copyFlow flow
            description: 复制 flow
            operationId: flow#copyFlow
            parameters:
                - name: id
                  in: path
                  description: 要复制的 flow id
                  required: true
                  schema:
                    type: string
                    description: 要复制的 flow id
                    example: Cupiditate et aut vero quia facilis saepe.
                  example: Aliquam dolorum et accusantium.
            responses:
                "201":
                    description: Created response.
components:
    schemas:
        AccountInfo:
            type: object
            properties:
                activated:
                    type: boolean
                    example: true
                membership:
                    type: integer
                    example: 6077889507282666396
                    format: int64
            example:
                activated: false
                membership: 5604669765176843498
            required:
                - activated
                - membership
        CreateFlowRequestBody:
            type: object
            properties:
                edges:
                    type: string
                    description: flow 边
                    example: Libero maxime.
                nodes:
                    type: string
                    description: flow 节点
                    example: Quas et voluptatum iure voluptas aperiam.
                title:
                    type: string
                    description: flow 标题
                    example: Porro nam ut.
            example:
                edges: Adipisci explicabo eveniet cum unde quam.
                nodes: In et fugiat.
                title: Veritatis vel voluptate rerum minus.
        FlowDetail:
            type: object
            properties:
                created_at:
                    type: string
                    description: flow 创建时间
                    example: Et neque ex.
                edges:
                    type: string
                    description: flow 边
                    example: Ipsum aut distinctio ipsa.
                id:
                    type: integer
                    description: flow id
                    example: 2327380425094630291
                    format: int64
                nodes:
                    type: string
                    description: flow 节点
                    example: Suscipit autem esse illo qui.
                title:
                    type: string
                    description: flow 标题
                    example: Molestias et fuga beatae.
            example:
                created_at: Id voluptatem quis nihil.
                edges: Adipisci ex.
                id: 4025439544900775537
                nodes: Fugiat magnam maxime repudiandae consequatur.
                title: Rerum reprehenderit.
            required:
                - id
                - title
                - created_at
        FlowListItem:
            type: object
            properties:
                created_at:
                    type: string
                    description: flow 创建时间
                    example: Exercitationem omnis ipsum deserunt architecto reiciendis.
                id:
                    type: integer
                    description: flow id
                    example: 450530213079432727
                    format: int64
                title:
                    type: string
                    description: flow 标题
                    example: Odio fuga voluptas voluptas minima.
            example:
                created_at: Voluptas optio consectetur quo possimus nobis.
                id: 1465049891302521045
                title: Odit voluptatem.
            required:
                - id
                - title
                - created_at
tags:
    - name: account
      description: Account service
    - name: flow
      description: Flow 服务
